language: node_js
node_js:
- '10'

before_install:
  - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc


jobs:
  include:
    - stage: install
      script: npm install
    - stage: build
      script: npm run build

stages:
  - install
  - build

#install:
#  - npm install
#
#script:
#  - npm run build
#  - npm i -g now
#  - now --build-env NPM_TOKEN=@npm-token

cache:
  - npm
  - yarn
