language: node_js
node_js:
- '10'

jobs:
  include:
    - stage: install
      script:
        - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
        - npm install
    - stage: build
      script: npm run build

