language: node_js
node_js:
- '10'

before_install:
  - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

install:
  - yarn install

jobs:
  include:
    - stage: build
      script:
        - npm run build
    - stage: deploy
      script:
        - npm i -g now
        - now --build-env NPM_TOKEN=@npm-token --token=$NOM_TOKEN
        - now alias --token=$NOM_TOKEN

stages:
#  - install
#  - build
  - name: deploy
    if: branch = master

cache:
  - npm
  - yarn
