language: node_js
node_js:
- '10'

install:
  - yarn install

jobs:
  include:
    - stage: build
      script:
        - npm run build
        - npm run test:percy
    - stage: deploy
      script:
        - npm i -g now
        - now --token=$NOW_TOKEN --team=basalt
        - now alias --token=$NOW_TOKEN --team=basalt

stages:
  - install
  - build
  - name: deploy
    if: branch = master

cache:
  - npm
  - yarn
