# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

#trigger:
#- master

variables:
  - group: Tokens

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- script: |
    npm install -g now
    now --token=$(NOW_TOKEN) --team=basalt
#    now alias --token=$(NOW_TOKEN) --team=basalt
  displayName: 'deploy'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/feature/azure'))
