on: deployment_status
name: Deploy & Test
jobs:
  test-percy:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: install post-deploy
      uses: docker://node:10.14.2
      with:
        entrypoint: yarn
        args: install
    - name: test:percy
      uses: docker://cypress/browsers:chrome67
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        BASE_URL: ${{ github.event.deployment_status.environment_url }}
      with:
        entrypoint: sh
        args: -c "echo 'The base url is ' && echo $BASE_URL && yarn test:percy"
